### ISSUE TITLE
The library lacks a OCRB font

### ISSUE THREAD

**Issue by ravage84** [ravage84/SwissPaymentSlipTcpdf#1]
Currently the library contains no OCRB font, which means an implementing developer must organize one in a TCPDF compatible format, add it to the TCPDF fonts libary and change the font of the code line.

This is quite uncool and makes the library not ready for production use (out of the box).

I do have such a font at hand but I'm not sure about the potential legal issues (licensing).
At best I find a free one or soneone could provide one.

**Comment by ravage84** [comment]
@peschee or @sprain do you have any idea if there was a (royalty) free version of the OCRB font for TCPDF (**not FPDF**)?

Sorry for bugging you guys, but I'm hoping you could have an idea because you worked on the class which this library is based on.

**Comment by sprain** [comment]
Well, there are many place where you can download this font. I don't know however if those are legal publishers.

http://hilfe.flexbuero.ch/kb/1165
http://www.ufonts.com/fonts/ocrb.html
http://antevi.ch/ocr-b-font-einzahlungsscheine/

**Comment by peschee** [comment]
This site seems to have the fonts certified by Postfinance officially. However, they're a paid version unfortunately http://www.ocrb.ch/

**Comment by ravage84** [comment]
Thanks for your links guys. That certainly will help developers who want to use SwissPaymentSlipTcpdf.

Digging a little bit further, I found the following on the German Wikipedia Page about OCR-B:

> Matthew Skala erstellte im Jahr 2006 mittels mftrace daraus eine TrueType-Version der Schrift, die mit allen heute gebräuchlichen Betriebssystemen benutzt werden kann.[2] Die Form dieser kostenlosen Schrift ist mit der offiziellen OCR-B 10 kompatibel, Größe und Abstände sind es nicht

http://de.wikipedia.org/wiki/OCR-B#Implementierungen

I presume at least some of the versions provided by the websites you linked to are based on this font.
Not sure though, if the size and spacing incompatibility mentioned on the Wikipedia page is a real problem.

Also there was a link to a free (as in libre & beer) version on the English Wikipedia page of OCR-B:
http://ansuz.sooke.bc.ca/page/fonts#ocrb

There was also a link to place where you can buy the font:
http://www.linotype.com/de/1283/OCRB-family.html?PHPSESSID=8b3e6bd87c6e61dec546aac473adfa0b

Since I still have no clear and (legally) reliable answer to the license question, I stay reluctant to including the font into SwissPaymentSlipTcpdf.

**Comment by ravage84** [comment]
For conversion of the OCR-B font in a TCPDF compatible format, follow the instructions on the [TCPDF website](http://www.tcpdf.org/fonts.php#Convert_a_font_for_TCPDF):

> **Convert a font for TCPDF**
> Using the addTTFfont() method you can directly create a TCPDF font starting from a TrueType, OpenType or Type1 font.
> NOTE: The 'fonts' folder must be writeable by the webserver.
> For example:
> `$fontname = $pdf->addTTFfont('/path-to-font/DejaVuSans.ttf', 'TrueTypeUnicode', '', 32);`
> Check the source code documentation of addTTFfont() for further information.

**Comment by ravage84** [comment]
To permanently convert a True Type Font into a TCPDF compatible format, use the following tool:
https://github.com/tecnickcom/TCPDF/blob/6.2.6/tools/tcpdf_addfont.php

After that you can add your converted font like this:
`$tcpdf->AddFont('ocrb10', '', 'path/to/font/ocrb.php');`

The following font could be converted successfully according to a user user of this library:
http://www.fontpalace.com/font-download/OcrB%2BRegular/

**Comment by sdespont** [comment]
Online tool to easily convert True Type Font into a TCPDF compatible format : http://www.xml-convert.com/en/convert-tff-font-to-afm-pfa-fpdf-tcpdf

**Comment by peschee** [comment]
@ravage84 Would you mind creating an entry in the README for this? I'm closing the issue. It seems we've gathered all the relevant information here.

**Comment by WouterSchoofs** [comment]
Hi All, 

I found this font: https://wehtt.am/ocr-b/

The payment slip is approved with this open source font.

**Comment by leifnel** [comment]
> I found this font: https://wehtt.am/ocr-b/
> 
Alas this is not available anymore, not the link, neither on the fonts-page on the site.
